package com.bigfix.schemas.relevance;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:01:11.304-06:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://schemas.bigfix.com/Relevance", name = "DashboardVariablePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DashboardVariablePortType {

    @ResponseWrapper(localName = "StoreSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariableResponse")
    @RequestWrapper(localName = "StoreSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariable")
    @WebMethod(operationName = "StoreSharedVariable")
    public Response<com.bigfix.schemas.relevance.StoreSharedVariableResponse> storeSharedVariableAsync(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "variableValue", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String variableValue,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "StoreSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariableResponse")
    @RequestWrapper(localName = "StoreSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariable")
    @WebMethod(operationName = "StoreSharedVariable")
    public Future<?> storeSharedVariableAsync(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "variableValue", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String variableValue,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.bigfix.schemas.relevance.StoreSharedVariableResponse> asyncHandler
    );

    @WebResult(name = "success", targetNamespace = "http://schemas.bigfix.com/Relevance")
    @ResponseWrapper(localName = "StoreSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariableResponse")
    @RequestWrapper(localName = "StoreSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.StoreSharedVariable")
    @WebMethod(operationName = "StoreSharedVariable", action = "http://schemas.bigfix.com/Relevance/soapaction")
    public boolean storeSharedVariable(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "variableValue", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String variableValue,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "DeleteSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariableResponse")
    @RequestWrapper(localName = "DeleteSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariable")
    @WebMethod(operationName = "DeleteSharedVariable")
    public Response<com.bigfix.schemas.relevance.DeleteSharedVariableResponse> deleteSharedVariableAsync(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "DeleteSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariableResponse")
    @RequestWrapper(localName = "DeleteSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariable")
    @WebMethod(operationName = "DeleteSharedVariable")
    public Future<?> deleteSharedVariableAsync(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.bigfix.schemas.relevance.DeleteSharedVariableResponse> asyncHandler
    );

    @WebResult(name = "success", targetNamespace = "http://schemas.bigfix.com/Relevance")
    @ResponseWrapper(localName = "DeleteSharedVariableResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariableResponse")
    @RequestWrapper(localName = "DeleteSharedVariable", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.DeleteSharedVariable")
    @WebMethod(operationName = "DeleteSharedVariable", action = "http://schemas.bigfix.com/Relevance/soapaction")
    public boolean deleteSharedVariable(
        @WebParam(name = "dashboardVariableIdentifier", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.DashboardVariableIdentifier dashboardVariableIdentifier,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );
}
