package com.bigfix.schemas.relevance;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:01:11.355-06:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://schemas.bigfix.com/Relevance", name = "RelevancePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface RelevancePortType {

    @ResponseWrapper(localName = "GetStructuredRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResultResponse")
    @RequestWrapper(localName = "GetStructuredRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResult")
    @WebMethod(operationName = "GetStructuredRelevanceResult")
    public Response<com.bigfix.schemas.relevance.GetStructuredRelevanceResultResponse> getStructuredRelevanceResultAsync(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "GetStructuredRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResultResponse")
    @RequestWrapper(localName = "GetStructuredRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResult")
    @WebMethod(operationName = "GetStructuredRelevanceResult")
    public Future<?> getStructuredRelevanceResultAsync(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.bigfix.schemas.relevance.GetStructuredRelevanceResultResponse> asyncHandler
    );

    @WebResult(name = "StructuredRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance")
    @ResponseWrapper(localName = "GetStructuredRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResultResponse")
    @RequestWrapper(localName = "GetStructuredRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetStructuredRelevanceResult")
    @WebMethod(operationName = "GetStructuredRelevanceResult", action = "http://schemas.bigfix.com/Relevance/soapaction")
    public com.bigfix.schemas.relevance.StructuredRelevanceResult getStructuredRelevanceResult(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "GetRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResultResponse")
    @RequestWrapper(localName = "GetRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResult")
    @WebMethod(operationName = "GetRelevanceResult")
    public Response<com.bigfix.schemas.relevance.GetRelevanceResultResponse> getRelevanceResultAsync(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "username", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String password
    );

    @ResponseWrapper(localName = "GetRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResultResponse")
    @RequestWrapper(localName = "GetRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResult")
    @WebMethod(operationName = "GetRelevanceResult")
    public Future<?> getRelevanceResultAsync(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "username", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String password,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.bigfix.schemas.relevance.GetRelevanceResultResponse> asyncHandler
    );

    @WebResult(name = "a", targetNamespace = "http://schemas.bigfix.com/Relevance")
    @ResponseWrapper(localName = "GetRelevanceResultResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResultResponse")
    @RequestWrapper(localName = "GetRelevanceResult", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.GetRelevanceResult")
    @WebMethod(operationName = "GetRelevanceResult", action = "http://schemas.bigfix.com/Relevance/soapaction")
    public java.util.List<java.lang.String> getRelevanceResult(
        @WebParam(name = "relevanceExpr", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String relevanceExpr,
        @WebParam(name = "username", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://schemas.bigfix.com/Relevance")
        java.lang.String password
    );
}
