package com.bigfix.schemas.relevance;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:01:11.370-06:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://schemas.bigfix.com/Relevance", name = "UserManagementPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserManagementPortType {

    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUserResponse")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUser")
    @WebMethod(operationName = "CreateUser")
    public Response<com.bigfix.schemas.relevance.CreateUserResponse> createUserAsync(
        @WebParam(name = "user", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.UserAccount user,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );

    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUserResponse")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUser")
    @WebMethod(operationName = "CreateUser")
    public Future<?> createUserAsync(
        @WebParam(name = "user", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.UserAccount user,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.bigfix.schemas.relevance.CreateUserResponse> asyncHandler
    );

    @WebResult(name = "success", targetNamespace = "http://schemas.bigfix.com/Relevance")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUserResponse")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://schemas.bigfix.com/Relevance", className = "com.bigfix.schemas.relevance.CreateUser")
    @WebMethod(operationName = "CreateUser", action = "http://schemas.bigfix.com/Relevance/soapaction")
    public boolean createUser(
        @WebParam(name = "user", targetNamespace = "http://schemas.bigfix.com/Relevance")
        com.bigfix.schemas.relevance.UserAccount user,
        @WebParam(name = "RequestHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        RequestHeader requestHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseHeaderElement", targetNamespace = "http://schemas.bigfix.com/Relevance", header = true)
        javax.xml.ws.Holder<ResponseHeader> responseHeader
    );
}
