//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.12 at 04:20:59 PM CDT 
//


package com.bigfix.schemas.bes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchComponentRelevance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchComponentRelevance">
 *   &lt;complexContent>
 *     &lt;extension base="{}SearchComponent">
 *       &lt;sequence>
 *         &lt;element name="Relevance" type="{}RelevanceString"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Comparison" type="{}TrueFalseComparison" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchComponentRelevance", propOrder = {
    "relevance"
})
public class SearchComponentRelevance
    extends SearchComponent
{

    @XmlElement(name = "Relevance", required = true)
    protected RelevanceString relevance;
    @XmlAttribute(name = "Comparison")
    protected TrueFalseComparison comparison;

    /**
     * Gets the value of the relevance property.
     * 
     * @return
     *     possible object is
     *     {@link RelevanceString }
     *     
     */
    public RelevanceString getRelevance() {
        return relevance;
    }

    /**
     * Sets the value of the relevance property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelevanceString }
     *     
     */
    public void setRelevance(RelevanceString value) {
        this.relevance = value;
    }

    /**
     * Gets the value of the comparison property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseComparison }
     *     
     */
    public TrueFalseComparison getComparison() {
        return comparison;
    }

    /**
     * Sets the value of the comparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseComparison }
     *     
     */
    public void setComparison(TrueFalseComparison value) {
        this.comparison = value;
    }

}
