//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.12 at 02:23:24 PM CDT 
//


package com.bigfix.schemas.bes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SitePermissionString.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SitePermissionString">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Owner"/>
 *     &lt;enumeration value="Reader"/>
 *     &lt;enumeration value="Writer"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SitePermissionString")
@XmlEnum
public enum SitePermissionString {

    @XmlEnumValue("Owner")
    OWNER("Owner"),
    @XmlEnumValue("Reader")
    READER("Reader"),
    @XmlEnumValue("Writer")
    WRITER("Writer"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    SitePermissionString(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SitePermissionString fromValue(String v) {
        for (SitePermissionString c: SitePermissionString.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
