//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.12 at 02:23:24 PM CDT 
//


package com.bigfix.schemas.bes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Site complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Site">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{}ObjectName"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Domain" type="{}Domain" minOccurs="0"/>
 *         &lt;element name="GlobalReadPermission" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Subscription" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Mode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                         &lt;enumeration value="All"/>
 *                         &lt;enumeration value="None"/>
 *                         &lt;enumeration value="AdHoc"/>
 *                         &lt;enumeration value="Custom"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CustomGroup" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice maxOccurs="unbounded">
 *                               &lt;element name="SearchComponentRelevance" type="{}SearchComponentRelevance"/>
 *                               &lt;element name="SearchComponentPropertyReference" type="{}SearchComponentPropertyReference"/>
 *                               &lt;element name="SearchComponentGroupReference" type="{}SearchComponentGroupReference"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                           &lt;attribute name="JoinByIntersection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SiteRelevance" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Site", propOrder = {
    "name",
    "description",
    "domain",
    "globalReadPermission",
    "subscription",
    "siteRelevance"
})
@XmlSeeAlso({
    com.bigfix.schemas.bes.BES.CustomSite.class,
    com.bigfix.schemas.bes.BES.ActionSite.class,
    com.bigfix.schemas.bes.BES.ExternalSite.class
})
public class Site {

    @XmlElement(name = "Name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Domain")
    protected String domain;
    @XmlElement(name = "GlobalReadPermission")
    protected Boolean globalReadPermission;
    @XmlElement(name = "Subscription")
    protected Site.Subscription subscription;
    @XmlElement(name = "SiteRelevance")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String siteRelevance;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the globalReadPermission property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGlobalReadPermission() {
        return globalReadPermission;
    }

    /**
     * Sets the value of the globalReadPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlobalReadPermission(Boolean value) {
        this.globalReadPermission = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link Site.Subscription }
     *     
     */
    public Site.Subscription getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Site.Subscription }
     *     
     */
    public void setSubscription(Site.Subscription value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the siteRelevance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteRelevance() {
        return siteRelevance;
    }

    /**
     * Sets the value of the siteRelevance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteRelevance(String value) {
        this.siteRelevance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Mode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *               &lt;enumeration value="All"/>
     *               &lt;enumeration value="None"/>
     *               &lt;enumeration value="AdHoc"/>
     *               &lt;enumeration value="Custom"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CustomGroup" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice maxOccurs="unbounded">
     *                     &lt;element name="SearchComponentRelevance" type="{}SearchComponentRelevance"/>
     *                     &lt;element name="SearchComponentPropertyReference" type="{}SearchComponentPropertyReference"/>
     *                     &lt;element name="SearchComponentGroupReference" type="{}SearchComponentGroupReference"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *                 &lt;attribute name="JoinByIntersection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mode",
        "customGroup"
    })
    public static class Subscription {

        @XmlElement(name = "Mode", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String mode;
        @XmlElement(name = "CustomGroup")
        protected Site.Subscription.CustomGroup customGroup;

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the customGroup property.
         * 
         * @return
         *     possible object is
         *     {@link Site.Subscription.CustomGroup }
         *     
         */
        public Site.Subscription.CustomGroup getCustomGroup() {
            return customGroup;
        }

        /**
         * Sets the value of the customGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link Site.Subscription.CustomGroup }
         *     
         */
        public void setCustomGroup(Site.Subscription.CustomGroup value) {
            this.customGroup = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice maxOccurs="unbounded">
         *           &lt;element name="SearchComponentRelevance" type="{}SearchComponentRelevance"/>
         *           &lt;element name="SearchComponentPropertyReference" type="{}SearchComponentPropertyReference"/>
         *           &lt;element name="SearchComponentGroupReference" type="{}SearchComponentGroupReference"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *       &lt;attribute name="JoinByIntersection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference"
        })
        public static class CustomGroup {

            @XmlElements({
                @XmlElement(name = "SearchComponentRelevance", type = SearchComponentRelevance.class),
                @XmlElement(name = "SearchComponentPropertyReference", type = SearchComponentPropertyReference.class),
                @XmlElement(name = "SearchComponentGroupReference", type = SearchComponentGroupReference.class)
            })
            protected List<SearchComponent> searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference;
            @XmlAttribute(name = "JoinByIntersection")
            protected Boolean joinByIntersection;

            /**
             * Gets the value of the searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSearchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SearchComponentRelevance }
             * {@link SearchComponentPropertyReference }
             * {@link SearchComponentGroupReference }
             * 
             * 
             */
            public List<SearchComponent> getSearchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference() {
                if (searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference == null) {
                    searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference = new ArrayList<SearchComponent>();
                }
                return this.searchComponentRelevanceOrSearchComponentPropertyReferenceOrSearchComponentGroupReference;
            }

            /**
             * Gets the value of the joinByIntersection property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isJoinByIntersection() {
                return joinByIntersection;
            }

            /**
             * Sets the value of the joinByIntersection property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setJoinByIntersection(Boolean value) {
                this.joinByIntersection = value;
            }

        }

    }

}
